// Tüm ikonlar lucide-react paketinden gelir (offline, tree-shake'lenebilir).
// Tek merkez: uygulama genelinde anlamsal adlarla içe aktarılır.
export {
  LayoutDashboard as DashboardIcon,
  Megaphone as MegaphoneIcon,
  Building2 as HospitalIcon,
  LogOut as LogoutIcon,
  Menu as MenuIcon,
  Plus as PlusIcon,
  Pencil as EditIcon,
  Trash2 as TrashIcon,
  X as CloseIcon,
  Check as CheckIcon,
  User as UserIcon,
  Calendar as CalendarIcon,
  Info as InfoIcon,
  HeartPulse as HeartPulseIcon,
  Clock as ClockIcon,
  MapPin as MapPinIcon,
  Phone as PhoneIcon,
  Eye as EyeIcon,
  EyeOff as EyeOffIcon,
  Bell as BellIcon,
  ChevronRight as ChevronRightIcon,
  ChevronLeft as ChevronLeftIcon,
  ShieldCheck as ShieldIcon,
  LoaderCircle as LoaderIcon,
  Sun as SunIcon,
  Moon as MoonIcon,
  PanelLeft as PanelLeftIcon,
} from "lucide-react";
